// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: accomodations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccomodation = `-- name: CreateAccomodation :one
insert into accomodations (url, title, image_url, board_uuid, user_uuid)
values ($1, $2, $3, $4, $5)
returning uuid, updated_at, created_at, url, title, image_url, notes, status, booking_reference, selected, board_uuid, user_uuid
`

type CreateAccomodationParams struct {
	Url       string
	Title     string
	ImageUrl  *string
	BoardUuid pgtype.UUID
	UserUuid  pgtype.UUID
}

func (q *Queries) CreateAccomodation(ctx context.Context, arg CreateAccomodationParams) (Accomodation, error) {
	row := q.db.QueryRow(ctx, createAccomodation,
		arg.Url,
		arg.Title,
		arg.ImageUrl,
		arg.BoardUuid,
		arg.UserUuid,
	)
	var i Accomodation
	err := row.Scan(
		&i.Uuid,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Url,
		&i.Title,
		&i.ImageUrl,
		&i.Notes,
		&i.Status,
		&i.BookingReference,
		&i.Selected,
		&i.BoardUuid,
		&i.UserUuid,
	)
	return i, err
}

const deleteAccomodationByUuid = `-- name: DeleteAccomodationByUuid :exec
delete from accomodations
where uuid = $1
`

func (q *Queries) DeleteAccomodationByUuid(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccomodationByUuid, uuid)
	return err
}

const findAllAccomodationsByBoardUuid = `-- name: FindAllAccomodationsByBoardUuid :many
select a.uuid, a.updated_at, a.created_at, a.url, a.title, a.image_url, a.notes, a.status, a.booking_reference, a.selected, a.board_uuid, a.user_uuid,
    coalesce(avg(v.rank)::float, 0)::float as avg_rating,
    count(v.uuid)::int as rating_count
from accomodations a
left join votes v on v.voted_on_uuid = a.uuid and v.voted_on_ = 'accomodation'
where a.board_uuid = $1
group by a.uuid
`

type FindAllAccomodationsByBoardUuidRow struct {
	Uuid             pgtype.UUID
	UpdatedAt        pgtype.Timestamp
	CreatedAt        pgtype.Timestamp
	Url              string
	Title            string
	ImageUrl         *string
	Notes            *string
	Status           AccomodationsStatus
	BookingReference *string
	Selected         bool
	BoardUuid        pgtype.UUID
	UserUuid         pgtype.UUID
	AvgRating        float64
	RatingCount      int32
}

func (q *Queries) FindAllAccomodationsByBoardUuid(ctx context.Context, boardUuid pgtype.UUID) ([]FindAllAccomodationsByBoardUuidRow, error) {
	rows, err := q.db.Query(ctx, findAllAccomodationsByBoardUuid, boardUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindAllAccomodationsByBoardUuidRow
	for rows.Next() {
		var i FindAllAccomodationsByBoardUuidRow
		if err := rows.Scan(
			&i.Uuid,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.Url,
			&i.Title,
			&i.ImageUrl,
			&i.Notes,
			&i.Status,
			&i.BookingReference,
			&i.Selected,
			&i.BoardUuid,
			&i.UserUuid,
			&i.AvgRating,
			&i.RatingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccomodationByUuid = `-- name: GetAccomodationByUuid :one
select a.uuid, a.updated_at, a.created_at, a.url, a.title, a.image_url, a.notes, a.status, a.booking_reference, a.selected, a.board_uuid, a.user_uuid,
    coalesce(avg(v.rank)::float, 0)::float as avg_rating,
    count(v.uuid)::int as rating_count
from accomodations a
left join votes v on v.voted_on_uuid = a.uuid and v.voted_on_ = 'accomodation'
where a.uuid = $1
group by a.uuid
`

type GetAccomodationByUuidRow struct {
	Uuid             pgtype.UUID
	UpdatedAt        pgtype.Timestamp
	CreatedAt        pgtype.Timestamp
	Url              string
	Title            string
	ImageUrl         *string
	Notes            *string
	Status           AccomodationsStatus
	BookingReference *string
	Selected         bool
	BoardUuid        pgtype.UUID
	UserUuid         pgtype.UUID
	AvgRating        float64
	RatingCount      int32
}

func (q *Queries) GetAccomodationByUuid(ctx context.Context, uuid pgtype.UUID) (GetAccomodationByUuidRow, error) {
	row := q.db.QueryRow(ctx, getAccomodationByUuid, uuid)
	var i GetAccomodationByUuidRow
	err := row.Scan(
		&i.Uuid,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Url,
		&i.Title,
		&i.ImageUrl,
		&i.Notes,
		&i.Status,
		&i.BookingReference,
		&i.Selected,
		&i.BoardUuid,
		&i.UserUuid,
		&i.AvgRating,
		&i.RatingCount,
	)
	return i, err
}

const updateAccomodationByUuid = `-- name: UpdateAccomodationByUuid :exec
update accomodations
set url = $1,
    title = $2,
    image_url = $3,
    notes = $4,
    status = $5,
    booking_reference = $6,
    selected = $7
where uuid = $8
`

type UpdateAccomodationByUuidParams struct {
	Url              string
	Title            string
	ImageUrl         *string
	Notes            *string
	Status           AccomodationsStatus
	BookingReference *string
	Selected         bool
	Uuid             pgtype.UUID
}

func (q *Queries) UpdateAccomodationByUuid(ctx context.Context, arg UpdateAccomodationByUuidParams) error {
	_, err := q.db.Exec(ctx, updateAccomodationByUuid,
		arg.Url,
		arg.Title,
		arg.ImageUrl,
		arg.Notes,
		arg.Status,
		arg.BookingReference,
		arg.Selected,
		arg.Uuid,
	)
	return err
}
