// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accomodations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findAllAccomodationsByBoardUuid = `-- name: FindAllAccomodationsByBoardUuid :many
select uuid, updated_at, created_at, url, title, image_url, notes, status, booking_reference, selected, board_uuid
from accomodations
where board_uuid = $1
`

func (q *Queries) FindAllAccomodationsByBoardUuid(ctx context.Context, boardUuid pgtype.UUID) ([]Accomodation, error) {
	rows, err := q.db.Query(ctx, findAllAccomodationsByBoardUuid, boardUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Accomodation
	for rows.Next() {
		var i Accomodation
		if err := rows.Scan(
			&i.Uuid,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.Url,
			&i.Title,
			&i.ImageUrl,
			&i.Notes,
			&i.Status,
			&i.BookingReference,
			&i.Selected,
			&i.BoardUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
