// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: activities.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createActivity = `-- name: CreateActivity :one
insert into activities (url, title, image_url, board_uuid, user_uuid)
values ($1, $2, $3, $4, $5)
returning uuid, updated_at, created_at, url, title, image_url, notes, status, booking_reference, selected, board_uuid, user_uuid
`

type CreateActivityParams struct {
	Url       string
	Title     string
	ImageUrl  *string
	BoardUuid pgtype.UUID
	UserUuid  pgtype.UUID
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, createActivity,
		arg.Url,
		arg.Title,
		arg.ImageUrl,
		arg.BoardUuid,
		arg.UserUuid,
	)
	var i Activity
	err := row.Scan(
		&i.Uuid,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Url,
		&i.Title,
		&i.ImageUrl,
		&i.Notes,
		&i.Status,
		&i.BookingReference,
		&i.Selected,
		&i.BoardUuid,
		&i.UserUuid,
	)
	return i, err
}

const deleteActivityByUuid = `-- name: DeleteActivityByUuid :exec
delete from activities
where uuid = $1
`

func (q *Queries) DeleteActivityByUuid(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteActivityByUuid, uuid)
	return err
}

const findAllActivitiesByBoardUuid = `-- name: FindAllActivitiesByBoardUuid :many
select a.uuid, a.updated_at, a.created_at, a.url, a.title, a.image_url, a.notes, a.status, a.booking_reference, a.selected, a.board_uuid, a.user_uuid,
    count(case when v.rank = 1 then 1 end)::int as likes,
    count(case when v.rank < 1 then 1 end)::int as dislikes
from activities a
left join votes v on v.voted_on_uuid = a.uuid and v.voted_on_ = 'activities'
where a.board_uuid = $1
group by a.uuid
`

type FindAllActivitiesByBoardUuidRow struct {
	Uuid             pgtype.UUID
	UpdatedAt        pgtype.Timestamp
	CreatedAt        pgtype.Timestamp
	Url              string
	Title            string
	ImageUrl         *string
	Notes            *string
	Status           ActivitiesStatus
	BookingReference *string
	Selected         bool
	BoardUuid        pgtype.UUID
	UserUuid         pgtype.UUID
	Likes            int32
	Dislikes         int32
}

func (q *Queries) FindAllActivitiesByBoardUuid(ctx context.Context, boardUuid pgtype.UUID) ([]FindAllActivitiesByBoardUuidRow, error) {
	rows, err := q.db.Query(ctx, findAllActivitiesByBoardUuid, boardUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindAllActivitiesByBoardUuidRow
	for rows.Next() {
		var i FindAllActivitiesByBoardUuidRow
		if err := rows.Scan(
			&i.Uuid,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.Url,
			&i.Title,
			&i.ImageUrl,
			&i.Notes,
			&i.Status,
			&i.BookingReference,
			&i.Selected,
			&i.BoardUuid,
			&i.UserUuid,
			&i.Likes,
			&i.Dislikes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActivityByUuid = `-- name: GetActivityByUuid :one
select a.uuid, a.updated_at, a.created_at, a.url, a.title, a.image_url, a.notes, a.status, a.booking_reference, a.selected, a.board_uuid, a.user_uuid,
    count(case when v.rank = 1 then 1 end)::int as likes,
    count(case when v.rank < 1 then 1 end)::int as dislikes
from activities a
left join votes v on v.voted_on_uuid = a.uuid and v.voted_on_ = 'activities'
where a.uuid = $1
group by a.uuid
`

type GetActivityByUuidRow struct {
	Uuid             pgtype.UUID
	UpdatedAt        pgtype.Timestamp
	CreatedAt        pgtype.Timestamp
	Url              string
	Title            string
	ImageUrl         *string
	Notes            *string
	Status           ActivitiesStatus
	BookingReference *string
	Selected         bool
	BoardUuid        pgtype.UUID
	UserUuid         pgtype.UUID
	Likes            int32
	Dislikes         int32
}

func (q *Queries) GetActivityByUuid(ctx context.Context, uuid pgtype.UUID) (GetActivityByUuidRow, error) {
	row := q.db.QueryRow(ctx, getActivityByUuid, uuid)
	var i GetActivityByUuidRow
	err := row.Scan(
		&i.Uuid,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Url,
		&i.Title,
		&i.ImageUrl,
		&i.Notes,
		&i.Status,
		&i.BookingReference,
		&i.Selected,
		&i.BoardUuid,
		&i.UserUuid,
		&i.Likes,
		&i.Dislikes,
	)
	return i, err
}

const updateActivityByUuid = `-- name: UpdateActivityByUuid :exec
update activities
set url = $1,
    title = $2,
    image_url = $3,
    notes = $4,
    status = $5,
    booking_reference = $6,
    selected = $7
where uuid = $8
`

type UpdateActivityByUuidParams struct {
	Url              string
	Title            string
	ImageUrl         *string
	Notes            *string
	Status           ActivitiesStatus
	BookingReference *string
	Selected         bool
	Uuid             pgtype.UUID
}

func (q *Queries) UpdateActivityByUuid(ctx context.Context, arg UpdateActivityByUuidParams) error {
	_, err := q.db.Exec(ctx, updateActivityByUuid,
		arg.Url,
		arg.Title,
		arg.ImageUrl,
		arg.Notes,
		arg.Status,
		arg.BookingReference,
		arg.Selected,
		arg.Uuid,
	)
	return err
}
