// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: boards.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBoard = `-- name: CreateBoard :one
insert into boards (name, location_name, user_uuid)
values ($1, $2, $3)
returning uuid, updated_at, created_at, name, details, location_name, starts_at, lasts_until, status, thumbnail_url, user_uuid
`

type CreateBoardParams struct {
	Name         string
	LocationName string
	UserUuid     pgtype.UUID
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, createBoard, arg.Name, arg.LocationName, arg.UserUuid)
	var i Board
	err := row.Scan(
		&i.Uuid,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Name,
		&i.Details,
		&i.LocationName,
		&i.StartsAt,
		&i.LastsUntil,
		&i.Status,
		&i.ThumbnailUrl,
		&i.UserUuid,
	)
	return i, err
}

const deleteBoardById = `-- name: DeleteBoardById :exec
delete from boards
where uuid = $1
`

func (q *Queries) DeleteBoardById(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBoardById, uuid)
	return err
}

const getAllBoards = `-- name: GetAllBoards :many
select b.uuid, b.updated_at, b.created_at, b.name, b.details, b.location_name, b.starts_at, b.lasts_until, b.status, b.thumbnail_url, b.user_uuid,
       (select count(*) from accomodations a where a.board_uuid = b.uuid) as accomodations_count,
       (select count(*) from transport t where t.board_uuid = b.uuid) as transport_count,
       (select count(*) from activities act where act.board_uuid = b.uuid) as activities_count
from boards b
where b.user_uuid = $1
`

type GetAllBoardsRow struct {
	Uuid               pgtype.UUID
	UpdatedAt          pgtype.Timestamp
	CreatedAt          pgtype.Timestamp
	Name               string
	Details            *string
	LocationName       string
	StartsAt           pgtype.Date
	LastsUntil         pgtype.Date
	Status             BoardsStatus
	ThumbnailUrl       *string
	UserUuid           pgtype.UUID
	AccomodationsCount int64
	TransportCount     int64
	ActivitiesCount    int64
}

func (q *Queries) GetAllBoards(ctx context.Context, userUuid pgtype.UUID) ([]GetAllBoardsRow, error) {
	rows, err := q.db.Query(ctx, getAllBoards, userUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllBoardsRow
	for rows.Next() {
		var i GetAllBoardsRow
		if err := rows.Scan(
			&i.Uuid,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.Name,
			&i.Details,
			&i.LocationName,
			&i.StartsAt,
			&i.LastsUntil,
			&i.Status,
			&i.ThumbnailUrl,
			&i.UserUuid,
			&i.AccomodationsCount,
			&i.TransportCount,
			&i.ActivitiesCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBoardById = `-- name: GetBoardById :one
select uuid, updated_at, created_at, name, details, location_name, starts_at, lasts_until, status, thumbnail_url, user_uuid
from boards
where uuid = $1
`

func (q *Queries) GetBoardById(ctx context.Context, uuid pgtype.UUID) (Board, error) {
	row := q.db.QueryRow(ctx, getBoardById, uuid)
	var i Board
	err := row.Scan(
		&i.Uuid,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Name,
		&i.Details,
		&i.LocationName,
		&i.StartsAt,
		&i.LastsUntil,
		&i.Status,
		&i.ThumbnailUrl,
		&i.UserUuid,
	)
	return i, err
}

const updateBoardById = `-- name: UpdateBoardById :exec
update boards
set name = $1,
    details = $2,
    location_name = $3,
    starts_at = $4,
    lasts_until = $5,
    thumbnail_url = $6
where uuid = $7
`

type UpdateBoardByIdParams struct {
	Name         string
	Details      *string
	LocationName string
	StartsAt     pgtype.Date
	LastsUntil   pgtype.Date
	ThumbnailUrl *string
	Uuid         pgtype.UUID
}

func (q *Queries) UpdateBoardById(ctx context.Context, arg UpdateBoardByIdParams) error {
	_, err := q.db.Exec(ctx, updateBoardById,
		arg.Name,
		arg.Details,
		arg.LocationName,
		arg.StartsAt,
		arg.LastsUntil,
		arg.ThumbnailUrl,
		arg.Uuid,
	)
	return err
}
