// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: boards.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBoard = `-- name: CreateBoard :one
insert into boards (name, location_name, user_uuid)
values ($1, $2, $3)
returning uuid, updated_at, created_at, name, details, location_name, starts_at, lasts_until, status, thumbnail_url, user_uuid
`

type CreateBoardParams struct {
	Name         string
	LocationName string
	UserUuid     pgtype.UUID
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, createBoard, arg.Name, arg.LocationName, arg.UserUuid)
	var i Board
	err := row.Scan(
		&i.Uuid,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Name,
		&i.Details,
		&i.LocationName,
		&i.StartsAt,
		&i.LastsUntil,
		&i.Status,
		&i.ThumbnailUrl,
		&i.UserUuid,
	)
	return i, err
}

const deleteBoardById = `-- name: DeleteBoardById :exec
delete from boards
where uuid = $1
`

func (q *Queries) DeleteBoardById(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBoardById, uuid)
	return err
}

const getAllBoards = `-- name: GetAllBoards :many
select uuid, updated_at, created_at, name, details, location_name, starts_at, lasts_until, status, thumbnail_url, user_uuid
from boards
`

func (q *Queries) GetAllBoards(ctx context.Context) ([]Board, error) {
	rows, err := q.db.Query(ctx, getAllBoards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Board
	for rows.Next() {
		var i Board
		if err := rows.Scan(
			&i.Uuid,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.Name,
			&i.Details,
			&i.LocationName,
			&i.StartsAt,
			&i.LastsUntil,
			&i.Status,
			&i.ThumbnailUrl,
			&i.UserUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBoardById = `-- name: GetBoardById :one
select uuid, updated_at, created_at, name, details, location_name, starts_at, lasts_until, status, thumbnail_url, user_uuid
from boards
where uuid = $1
`

func (q *Queries) GetBoardById(ctx context.Context, uuid pgtype.UUID) (Board, error) {
	row := q.db.QueryRow(ctx, getBoardById, uuid)
	var i Board
	err := row.Scan(
		&i.Uuid,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Name,
		&i.Details,
		&i.LocationName,
		&i.StartsAt,
		&i.LastsUntil,
		&i.Status,
		&i.ThumbnailUrl,
		&i.UserUuid,
	)
	return i, err
}

const updateBoardById = `-- name: UpdateBoardById :exec
update boards
set name = $1,
    details = $2,
    location_name = $3,
    starts_at = $4,
    lasts_until = $5,
    thumbnail_url = $6
where uuid = $7
`

type UpdateBoardByIdParams struct {
	Name         string
	Details      *string
	LocationName string
	StartsAt     pgtype.Date
	LastsUntil   pgtype.Date
	ThumbnailUrl *string
	Uuid         pgtype.UUID
}

func (q *Queries) UpdateBoardById(ctx context.Context, arg UpdateBoardByIdParams) error {
	_, err := q.db.Exec(ctx, updateBoardById,
		arg.Name,
		arg.Details,
		arg.LocationName,
		arg.StartsAt,
		arg.LastsUntil,
		arg.ThumbnailUrl,
		arg.Uuid,
	)
	return err
}
