// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: comments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
insert into comments (created_by, content, commented_on_, commented_on_uuid)
values ($1, $2, $3, $4)
returning uuid, updated_at, created_at, created_by, content, commented_on_, commented_on_uuid
`

type CreateCommentParams struct {
	CreatedBy       pgtype.UUID
	Content         string
	CommentedOn     CommentedOn
	CommentedOnUuid pgtype.UUID
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.CreatedBy,
		arg.Content,
		arg.CommentedOn,
		arg.CommentedOnUuid,
	)
	var i Comment
	err := row.Scan(
		&i.Uuid,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.Content,
		&i.CommentedOn,
		&i.CommentedOnUuid,
	)
	return i, err
}

const deleteCommentByUuid = `-- name: DeleteCommentByUuid :exec
delete from comments
where uuid = $1
`

func (q *Queries) DeleteCommentByUuid(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCommentByUuid, uuid)
	return err
}

const findAllCommentsByCommentedOnUuid = `-- name: FindAllCommentsByCommentedOnUuid :many
select c.uuid, c.updated_at, c.created_at, c.created_by, c.content, c.commented_on_, c.commented_on_uuid, u.name as user_name
from comments c
join users u on c.created_by = u.uuid
where c.commented_on_ = $1 
    and c.commented_on_uuid = $2
`

type FindAllCommentsByCommentedOnUuidParams struct {
	CommentedOn     CommentedOn
	CommentedOnUuid pgtype.UUID
}

type FindAllCommentsByCommentedOnUuidRow struct {
	Uuid            pgtype.UUID
	UpdatedAt       pgtype.Timestamp
	CreatedAt       pgtype.Timestamp
	CreatedBy       pgtype.UUID
	Content         string
	CommentedOn     CommentedOn
	CommentedOnUuid pgtype.UUID
	UserName        string
}

func (q *Queries) FindAllCommentsByCommentedOnUuid(ctx context.Context, arg FindAllCommentsByCommentedOnUuidParams) ([]FindAllCommentsByCommentedOnUuidRow, error) {
	rows, err := q.db.Query(ctx, findAllCommentsByCommentedOnUuid, arg.CommentedOn, arg.CommentedOnUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindAllCommentsByCommentedOnUuidRow
	for rows.Next() {
		var i FindAllCommentsByCommentedOnUuidRow
		if err := rows.Scan(
			&i.Uuid,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.Content,
			&i.CommentedOn,
			&i.CommentedOnUuid,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCommentByUuid = `-- name: UpdateCommentByUuid :exec
update comments
set content = $1
where uuid = $2
`

type UpdateCommentByUuidParams struct {
	Content string
	Uuid    pgtype.UUID
}

func (q *Queries) UpdateCommentByUuid(ctx context.Context, arg UpdateCommentByUuidParams) error {
	_, err := q.db.Exec(ctx, updateCommentByUuid, arg.Content, arg.Uuid)
	return err
}
