// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: memories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMemory = `-- name: CreateMemory :one
insert into memories (board_uuid, uploaded_by, image_url)
values ($1, $2, $3)
returning uuid, updated_at, created_at, uploaded_by, board_uuid, image_url
`

type CreateMemoryParams struct {
	BoardUuid  pgtype.UUID
	UploadedBy pgtype.UUID
	ImageUrl   string
}

func (q *Queries) CreateMemory(ctx context.Context, arg CreateMemoryParams) (Memory, error) {
	row := q.db.QueryRow(ctx, createMemory, arg.BoardUuid, arg.UploadedBy, arg.ImageUrl)
	var i Memory
	err := row.Scan(
		&i.Uuid,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.UploadedBy,
		&i.BoardUuid,
		&i.ImageUrl,
	)
	return i, err
}

const deleteMemoryByUuid = `-- name: DeleteMemoryByUuid :exec
delete from memories
where uuid = $1
`

func (q *Queries) DeleteMemoryByUuid(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMemoryByUuid, uuid)
	return err
}

const findAllMemoriesByBoardUuid = `-- name: FindAllMemoriesByBoardUuid :many
select uuid, updated_at, created_at, uploaded_by, board_uuid, image_url from memories
where board_uuid = $1
order by created_at desc
`

func (q *Queries) FindAllMemoriesByBoardUuid(ctx context.Context, boardUuid pgtype.UUID) ([]Memory, error) {
	rows, err := q.db.Query(ctx, findAllMemoriesByBoardUuid, boardUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Memory
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.Uuid,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.UploadedBy,
			&i.BoardUuid,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemoryByUuid = `-- name: GetMemoryByUuid :one
select uuid, updated_at, created_at, uploaded_by, board_uuid, image_url from memories
where uuid = $1
`

func (q *Queries) GetMemoryByUuid(ctx context.Context, uuid pgtype.UUID) (Memory, error) {
	row := q.db.QueryRow(ctx, getMemoryByUuid, uuid)
	var i Memory
	err := row.Scan(
		&i.Uuid,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.UploadedBy,
		&i.BoardUuid,
		&i.ImageUrl,
	)
	return i, err
}
