// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccomodationsStatus string

const (
	AccomodationsStatusConsidering AccomodationsStatus = "considering"
	AccomodationsStatusFinalist    AccomodationsStatus = "finalist"
	AccomodationsStatusRejected    AccomodationsStatus = "rejected"
	AccomodationsStatusBooked      AccomodationsStatus = "booked"
	AccomodationsStatusCompleted   AccomodationsStatus = "completed"
)

func (e *AccomodationsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccomodationsStatus(s)
	case string:
		*e = AccomodationsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AccomodationsStatus: %T", src)
	}
	return nil
}

type NullAccomodationsStatus struct {
	AccomodationsStatus AccomodationsStatus
	Valid               bool // Valid is true if AccomodationsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccomodationsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AccomodationsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccomodationsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccomodationsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccomodationsStatus), nil
}

type ActivitiesStatus string

const (
	ActivitiesStatusConsidering ActivitiesStatus = "considering"
	ActivitiesStatusFinalist    ActivitiesStatus = "finalist"
	ActivitiesStatusRejected    ActivitiesStatus = "rejected"
	ActivitiesStatusBooked      ActivitiesStatus = "booked"
	ActivitiesStatusCompleted   ActivitiesStatus = "completed"
)

func (e *ActivitiesStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActivitiesStatus(s)
	case string:
		*e = ActivitiesStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ActivitiesStatus: %T", src)
	}
	return nil
}

type NullActivitiesStatus struct {
	ActivitiesStatus ActivitiesStatus
	Valid            bool // Valid is true if ActivitiesStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActivitiesStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ActivitiesStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActivitiesStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActivitiesStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActivitiesStatus), nil
}

type BoardsStatus string

const (
	BoardsStatusPlanning  BoardsStatus = "planning"
	BoardsStatusCancelled BoardsStatus = "cancelled"
	BoardsStatusCompleted BoardsStatus = "completed"
)

func (e *BoardsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BoardsStatus(s)
	case string:
		*e = BoardsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BoardsStatus: %T", src)
	}
	return nil
}

type NullBoardsStatus struct {
	BoardsStatus BoardsStatus
	Valid        bool // Valid is true if BoardsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBoardsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BoardsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BoardsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBoardsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BoardsStatus), nil
}

type CommentedOn string

const (
	CommentedOnAccomodation CommentedOn = "accomodation"
	CommentedOnTransport    CommentedOn = "transport"
	CommentedOnActivities   CommentedOn = "activities"
)

func (e *CommentedOn) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CommentedOn(s)
	case string:
		*e = CommentedOn(s)
	default:
		return fmt.Errorf("unsupported scan type for CommentedOn: %T", src)
	}
	return nil
}

type NullCommentedOn struct {
	CommentedOn CommentedOn
	Valid       bool // Valid is true if CommentedOn is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCommentedOn) Scan(value interface{}) error {
	if value == nil {
		ns.CommentedOn, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CommentedOn.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCommentedOn) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CommentedOn), nil
}

type ScrapeStatus string

const (
	ScrapeStatusProcessing                 ScrapeStatus = "processing"
	ScrapeStatusCompletedByOg              ScrapeStatus = "completed_by_og"
	ScrapeStatusCompletedByJsonLd          ScrapeStatus = "completed_by_json_ld"
	ScrapeStatusCompletedByAi              ScrapeStatus = "completed_by_ai"
	ScrapeStatusFailed                     ScrapeStatus = "failed"
	ScrapeStatusCompletedByImageExtraction ScrapeStatus = "completed_by_image_extraction"
)

func (e *ScrapeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScrapeStatus(s)
	case string:
		*e = ScrapeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ScrapeStatus: %T", src)
	}
	return nil
}

type NullScrapeStatus struct {
	ScrapeStatus ScrapeStatus
	Valid        bool // Valid is true if ScrapeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScrapeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ScrapeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScrapeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScrapeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScrapeStatus), nil
}

type TransportStatus string

const (
	TransportStatusConsidering TransportStatus = "considering"
	TransportStatusFinalist    TransportStatus = "finalist"
	TransportStatusRejected    TransportStatus = "rejected"
	TransportStatusBooked      TransportStatus = "booked"
	TransportStatusCompleted   TransportStatus = "completed"
)

func (e *TransportStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransportStatus(s)
	case string:
		*e = TransportStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TransportStatus: %T", src)
	}
	return nil
}

type NullTransportStatus struct {
	TransportStatus TransportStatus
	Valid           bool // Valid is true if TransportStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransportStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TransportStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransportStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransportStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransportStatus), nil
}

type VotedOn string

const (
	VotedOnAccomodation VotedOn = "accomodation"
	VotedOnTransport    VotedOn = "transport"
	VotedOnActivities   VotedOn = "activities"
)

func (e *VotedOn) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VotedOn(s)
	case string:
		*e = VotedOn(s)
	default:
		return fmt.Errorf("unsupported scan type for VotedOn: %T", src)
	}
	return nil
}

type NullVotedOn struct {
	VotedOn VotedOn
	Valid   bool // Valid is true if VotedOn is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVotedOn) Scan(value interface{}) error {
	if value == nil {
		ns.VotedOn, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VotedOn.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVotedOn) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VotedOn), nil
}

type Accomodation struct {
	Uuid             pgtype.UUID
	UpdatedAt        pgtype.Timestamp
	CreatedAt        pgtype.Timestamp
	Url              string
	Title            string
	ImageUrl         *string
	Notes            *string
	Status           AccomodationsStatus
	BookingReference *string
	Selected         bool
	BoardUuid        pgtype.UUID
	UserUuid         pgtype.UUID
}

type Activity struct {
	Uuid             pgtype.UUID
	UpdatedAt        pgtype.Timestamp
	CreatedAt        pgtype.Timestamp
	Url              string
	Title            string
	ImageUrl         *string
	Notes            *string
	Status           ActivitiesStatus
	BookingReference *string
	Selected         bool
	BoardUuid        pgtype.UUID
	UserUuid         pgtype.UUID
}

type Board struct {
	Uuid         pgtype.UUID
	UpdatedAt    pgtype.Timestamp
	CreatedAt    pgtype.Timestamp
	Name         string
	Details      *string
	LocationName string
	StartsAt     pgtype.Date
	LastsUntil   pgtype.Date
	Status       BoardsStatus
	ThumbnailUrl *string
	UserUuid     pgtype.UUID
}

type Comment struct {
	Uuid            pgtype.UUID
	UpdatedAt       pgtype.Timestamp
	CreatedAt       pgtype.Timestamp
	CreatedBy       pgtype.UUID
	Content         string
	CommentedOn     CommentedOn
	CommentedOnUuid pgtype.UUID
}

type Memory struct {
	Uuid       pgtype.UUID
	UpdatedAt  pgtype.Timestamp
	CreatedAt  pgtype.Timestamp
	UploadedBy pgtype.UUID
	BoardUuid  pgtype.UUID
	ImageUrl   string
}

type ScrapeAudit struct {
	Uuid        pgtype.UUID
	UpdatedAt   pgtype.Timestamp
	CreatedAt   pgtype.Timestamp
	Url         string
	Status      ScrapeStatus
	Host        string
	Title       *string
	ImageUrl    *string
	Description *string
	SiteName    *string
}

type ShareToken struct {
	Token     string
	BoardUuid pgtype.UUID
	CreatedAt pgtype.Timestamp
}

type Transport struct {
	Uuid             pgtype.UUID
	UpdatedAt        pgtype.Timestamp
	CreatedAt        pgtype.Timestamp
	Url              string
	Title            string
	ImageUrl         *string
	Notes            *string
	Status           TransportStatus
	BookingReference *string
	Selected         bool
	BoardUuid        pgtype.UUID
	UserUuid         pgtype.UUID
}

type User struct {
	Uuid      pgtype.UUID
	UpdatedAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
	Email     *string
	Name      string
	AvatarUrl *string
}

type Vote struct {
	Uuid        pgtype.UUID
	UpdatedAt   pgtype.Timestamp
	CreatedAt   pgtype.Timestamp
	VotedBy     pgtype.UUID
	Rank        int32
	VotedOn     VotedOn
	VotedOnUuid pgtype.UUID
}
