// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: scrape_audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScrapeAudit = `-- name: CreateScrapeAudit :one
insert into scrape_audit (url, host)
values ($1, $2)
returning uuid, updated_at, created_at, url, status, host, title, image_url, description, site_name
`

type CreateScrapeAuditParams struct {
	Url  string
	Host string
}

func (q *Queries) CreateScrapeAudit(ctx context.Context, arg CreateScrapeAuditParams) (ScrapeAudit, error) {
	row := q.db.QueryRow(ctx, createScrapeAudit, arg.Url, arg.Host)
	var i ScrapeAudit
	err := row.Scan(
		&i.Uuid,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Url,
		&i.Status,
		&i.Host,
		&i.Title,
		&i.ImageUrl,
		&i.Description,
		&i.SiteName,
	)
	return i, err
}

const updateScrapeAuditByUuid = `-- name: UpdateScrapeAuditByUuid :exec
update scrape_audit
set status = $1,
    title = $2,
    image_url = $3,
    description = $4,
    site_name = $5
where uuid = $6
`

type UpdateScrapeAuditByUuidParams struct {
	Status      ScrapeStatus
	Title       *string
	ImageUrl    *string
	Description *string
	SiteName    *string
	Uuid        pgtype.UUID
}

func (q *Queries) UpdateScrapeAuditByUuid(ctx context.Context, arg UpdateScrapeAuditByUuidParams) error {
	_, err := q.db.Exec(ctx, updateScrapeAuditByUuid,
		arg.Status,
		arg.Title,
		arg.ImageUrl,
		arg.Description,
		arg.SiteName,
		arg.Uuid,
	)
	return err
}
