// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: share_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShareToken = `-- name: CreateShareToken :one
INSERT INTO share_tokens (token, board_uuid)
VALUES ($1, $2)
RETURNING token, board_uuid, created_at
`

type CreateShareTokenParams struct {
	Token     string
	BoardUuid pgtype.UUID
}

func (q *Queries) CreateShareToken(ctx context.Context, arg CreateShareTokenParams) (ShareToken, error) {
	row := q.db.QueryRow(ctx, createShareToken, arg.Token, arg.BoardUuid)
	var i ShareToken
	err := row.Scan(&i.Token, &i.BoardUuid, &i.CreatedAt)
	return i, err
}

const deleteShareToken = `-- name: DeleteShareToken :exec
DELETE FROM share_tokens WHERE token = $1 AND board_uuid = $2
`

type DeleteShareTokenParams struct {
	Token     string
	BoardUuid pgtype.UUID
}

func (q *Queries) DeleteShareToken(ctx context.Context, arg DeleteShareTokenParams) error {
	_, err := q.db.Exec(ctx, deleteShareToken, arg.Token, arg.BoardUuid)
	return err
}

const getShareToken = `-- name: GetShareToken :one
SELECT token, board_uuid, created_at FROM share_tokens WHERE token = $1 LIMIT 1
`

func (q *Queries) GetShareToken(ctx context.Context, token string) (ShareToken, error) {
	row := q.db.QueryRow(ctx, getShareToken, token)
	var i ShareToken
	err := row.Scan(&i.Token, &i.BoardUuid, &i.CreatedAt)
	return i, err
}

const getShareTokensForBoard = `-- name: GetShareTokensForBoard :many
SELECT token, board_uuid, created_at FROM share_tokens WHERE board_uuid = $1 ORDER BY created_at DESC
`

func (q *Queries) GetShareTokensForBoard(ctx context.Context, boardUuid pgtype.UUID) ([]ShareToken, error) {
	rows, err := q.db.Query(ctx, getShareTokensForBoard, boardUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShareToken
	for rows.Next() {
		var i ShareToken
		if err := rows.Scan(&i.Token, &i.BoardUuid, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
