// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: transport.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransport = `-- name: CreateTransport :one
insert into transport (
    url,
    title,
    image_url,
    board_uuid,
    user_uuid,
    outbound_departing_location,
    outbound_arriving_location,
    outbound_departing_at,
    outbound_arriving_at,
    inbound_departing_location,
    inbound_arriving_location,
    inbound_departing_at,
    inbound_arriving_at
)
values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
returning uuid, updated_at, created_at, url, title, image_url, notes, status, booking_reference, selected, board_uuid, user_uuid, outbound_departing_location, outbound_arriving_location, outbound_departing_at, outbound_arriving_at, inbound_departing_location, inbound_arriving_location, inbound_departing_at, inbound_arriving_at
`

type CreateTransportParams struct {
	Url                       string
	Title                     string
	ImageUrl                  *string
	BoardUuid                 pgtype.UUID
	UserUuid                  pgtype.UUID
	OutboundDepartingLocation *string
	OutboundArrivingLocation  *string
	OutboundDepartingAt       pgtype.Timestamptz
	OutboundArrivingAt        pgtype.Timestamptz
	InboundDepartingLocation  *string
	InboundArrivingLocation   *string
	InboundDepartingAt        pgtype.Timestamptz
	InboundArrivingAt         pgtype.Timestamptz
}

func (q *Queries) CreateTransport(ctx context.Context, arg CreateTransportParams) (Transport, error) {
	row := q.db.QueryRow(ctx, createTransport,
		arg.Url,
		arg.Title,
		arg.ImageUrl,
		arg.BoardUuid,
		arg.UserUuid,
		arg.OutboundDepartingLocation,
		arg.OutboundArrivingLocation,
		arg.OutboundDepartingAt,
		arg.OutboundArrivingAt,
		arg.InboundDepartingLocation,
		arg.InboundArrivingLocation,
		arg.InboundDepartingAt,
		arg.InboundArrivingAt,
	)
	var i Transport
	err := row.Scan(
		&i.Uuid,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Url,
		&i.Title,
		&i.ImageUrl,
		&i.Notes,
		&i.Status,
		&i.BookingReference,
		&i.Selected,
		&i.BoardUuid,
		&i.UserUuid,
		&i.OutboundDepartingLocation,
		&i.OutboundArrivingLocation,
		&i.OutboundDepartingAt,
		&i.OutboundArrivingAt,
		&i.InboundDepartingLocation,
		&i.InboundArrivingLocation,
		&i.InboundDepartingAt,
		&i.InboundArrivingAt,
	)
	return i, err
}

const deleteTransportByUuid = `-- name: DeleteTransportByUuid :exec
delete from transport
where uuid = $1
`

func (q *Queries) DeleteTransportByUuid(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTransportByUuid, uuid)
	return err
}

const findAllTransportByBoardUuid = `-- name: FindAllTransportByBoardUuid :many
select t.uuid, t.updated_at, t.created_at, t.url, t.title, t.image_url, t.notes, t.status, t.booking_reference, t.selected, t.board_uuid, t.user_uuid, t.outbound_departing_location, t.outbound_arriving_location, t.outbound_departing_at, t.outbound_arriving_at, t.inbound_departing_location, t.inbound_arriving_location, t.inbound_departing_at, t.inbound_arriving_at,
    coalesce(avg(v.rank)::float, 0)::float as avg_rating,
    count(v.uuid)::int as rating_count
from transport t
left join votes v on v.voted_on_uuid = t.uuid and v.voted_on_ = 'transport'
where t.board_uuid = $1
group by t.uuid
`

type FindAllTransportByBoardUuidRow struct {
	Uuid                      pgtype.UUID
	UpdatedAt                 pgtype.Timestamp
	CreatedAt                 pgtype.Timestamp
	Url                       string
	Title                     string
	ImageUrl                  *string
	Notes                     *string
	Status                    TransportStatus
	BookingReference          *string
	Selected                  bool
	BoardUuid                 pgtype.UUID
	UserUuid                  pgtype.UUID
	OutboundDepartingLocation *string
	OutboundArrivingLocation  *string
	OutboundDepartingAt       pgtype.Timestamptz
	OutboundArrivingAt        pgtype.Timestamptz
	InboundDepartingLocation  *string
	InboundArrivingLocation   *string
	InboundDepartingAt        pgtype.Timestamptz
	InboundArrivingAt         pgtype.Timestamptz
	AvgRating                 float64
	RatingCount               int32
}

func (q *Queries) FindAllTransportByBoardUuid(ctx context.Context, boardUuid pgtype.UUID) ([]FindAllTransportByBoardUuidRow, error) {
	rows, err := q.db.Query(ctx, findAllTransportByBoardUuid, boardUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindAllTransportByBoardUuidRow
	for rows.Next() {
		var i FindAllTransportByBoardUuidRow
		if err := rows.Scan(
			&i.Uuid,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.Url,
			&i.Title,
			&i.ImageUrl,
			&i.Notes,
			&i.Status,
			&i.BookingReference,
			&i.Selected,
			&i.BoardUuid,
			&i.UserUuid,
			&i.OutboundDepartingLocation,
			&i.OutboundArrivingLocation,
			&i.OutboundDepartingAt,
			&i.OutboundArrivingAt,
			&i.InboundDepartingLocation,
			&i.InboundArrivingLocation,
			&i.InboundDepartingAt,
			&i.InboundArrivingAt,
			&i.AvgRating,
			&i.RatingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransportByUuid = `-- name: GetTransportByUuid :one
select t.uuid, t.updated_at, t.created_at, t.url, t.title, t.image_url, t.notes, t.status, t.booking_reference, t.selected, t.board_uuid, t.user_uuid, t.outbound_departing_location, t.outbound_arriving_location, t.outbound_departing_at, t.outbound_arriving_at, t.inbound_departing_location, t.inbound_arriving_location, t.inbound_departing_at, t.inbound_arriving_at,
    coalesce(avg(v.rank)::float, 0)::float as avg_rating,
    count(v.uuid)::int as rating_count
from transport t
left join votes v on v.voted_on_uuid = t.uuid and v.voted_on_ = 'transport'
where t.uuid = $1
group by t.uuid
`

type GetTransportByUuidRow struct {
	Uuid                      pgtype.UUID
	UpdatedAt                 pgtype.Timestamp
	CreatedAt                 pgtype.Timestamp
	Url                       string
	Title                     string
	ImageUrl                  *string
	Notes                     *string
	Status                    TransportStatus
	BookingReference          *string
	Selected                  bool
	BoardUuid                 pgtype.UUID
	UserUuid                  pgtype.UUID
	OutboundDepartingLocation *string
	OutboundArrivingLocation  *string
	OutboundDepartingAt       pgtype.Timestamptz
	OutboundArrivingAt        pgtype.Timestamptz
	InboundDepartingLocation  *string
	InboundArrivingLocation   *string
	InboundDepartingAt        pgtype.Timestamptz
	InboundArrivingAt         pgtype.Timestamptz
	AvgRating                 float64
	RatingCount               int32
}

func (q *Queries) GetTransportByUuid(ctx context.Context, uuid pgtype.UUID) (GetTransportByUuidRow, error) {
	row := q.db.QueryRow(ctx, getTransportByUuid, uuid)
	var i GetTransportByUuidRow
	err := row.Scan(
		&i.Uuid,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Url,
		&i.Title,
		&i.ImageUrl,
		&i.Notes,
		&i.Status,
		&i.BookingReference,
		&i.Selected,
		&i.BoardUuid,
		&i.UserUuid,
		&i.OutboundDepartingLocation,
		&i.OutboundArrivingLocation,
		&i.OutboundDepartingAt,
		&i.OutboundArrivingAt,
		&i.InboundDepartingLocation,
		&i.InboundArrivingLocation,
		&i.InboundDepartingAt,
		&i.InboundArrivingAt,
		&i.AvgRating,
		&i.RatingCount,
	)
	return i, err
}

const updateTransportByUuid = `-- name: UpdateTransportByUuid :exec
update transport
set url = $1,
    title = $2,
    image_url = $3,
    notes = $4,
    status = $5,
    booking_reference = $6,
    selected = $7,
    outbound_departing_location = $8,
    outbound_arriving_location = $9,
    outbound_departing_at = $10,
    outbound_arriving_at = $11,
    inbound_departing_location = $12,
    inbound_arriving_location = $13,
    inbound_departing_at = $14,
    inbound_arriving_at = $15
where uuid = $16
`

type UpdateTransportByUuidParams struct {
	Url                       string
	Title                     string
	ImageUrl                  *string
	Notes                     *string
	Status                    TransportStatus
	BookingReference          *string
	Selected                  bool
	OutboundDepartingLocation *string
	OutboundArrivingLocation  *string
	OutboundDepartingAt       pgtype.Timestamptz
	OutboundArrivingAt        pgtype.Timestamptz
	InboundDepartingLocation  *string
	InboundArrivingLocation   *string
	InboundDepartingAt        pgtype.Timestamptz
	InboundArrivingAt         pgtype.Timestamptz
	Uuid                      pgtype.UUID
}

func (q *Queries) UpdateTransportByUuid(ctx context.Context, arg UpdateTransportByUuidParams) error {
	_, err := q.db.Exec(ctx, updateTransportByUuid,
		arg.Url,
		arg.Title,
		arg.ImageUrl,
		arg.Notes,
		arg.Status,
		arg.BookingReference,
		arg.Selected,
		arg.OutboundDepartingLocation,
		arg.OutboundArrivingLocation,
		arg.OutboundDepartingAt,
		arg.OutboundArrivingAt,
		arg.InboundDepartingLocation,
		arg.InboundArrivingLocation,
		arg.InboundDepartingAt,
		arg.InboundArrivingAt,
		arg.Uuid,
	)
	return err
}
