// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: transport.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransport = `-- name: CreateTransport :one
insert into transport (url, title, image_url, board_uuid)
values ($1, $2, $3, $4)
returning uuid, updated_at, created_at, url, title, image_url, notes, status, booking_reference, selected, board_uuid
`

type CreateTransportParams struct {
	Url       string
	Title     string
	ImageUrl  *string
	BoardUuid pgtype.UUID
}

func (q *Queries) CreateTransport(ctx context.Context, arg CreateTransportParams) (Transport, error) {
	row := q.db.QueryRow(ctx, createTransport,
		arg.Url,
		arg.Title,
		arg.ImageUrl,
		arg.BoardUuid,
	)
	var i Transport
	err := row.Scan(
		&i.Uuid,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Url,
		&i.Title,
		&i.ImageUrl,
		&i.Notes,
		&i.Status,
		&i.BookingReference,
		&i.Selected,
		&i.BoardUuid,
	)
	return i, err
}

const deleteTransportByUuid = `-- name: DeleteTransportByUuid :exec
delete from transport
where uuid = $1
`

func (q *Queries) DeleteTransportByUuid(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTransportByUuid, uuid)
	return err
}

const findAllTransportByBoardUuid = `-- name: FindAllTransportByBoardUuid :many
select uuid, updated_at, created_at, url, title, image_url, notes, status, booking_reference, selected, board_uuid
from transport
where board_uuid = $1
`

func (q *Queries) FindAllTransportByBoardUuid(ctx context.Context, boardUuid pgtype.UUID) ([]Transport, error) {
	rows, err := q.db.Query(ctx, findAllTransportByBoardUuid, boardUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transport
	for rows.Next() {
		var i Transport
		if err := rows.Scan(
			&i.Uuid,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.Url,
			&i.Title,
			&i.ImageUrl,
			&i.Notes,
			&i.Status,
			&i.BookingReference,
			&i.Selected,
			&i.BoardUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransportByUuid = `-- name: GetTransportByUuid :one
select uuid, updated_at, created_at, url, title, image_url, notes, status, booking_reference, selected, board_uuid
from transport
where uuid = $1
`

func (q *Queries) GetTransportByUuid(ctx context.Context, uuid pgtype.UUID) (Transport, error) {
	row := q.db.QueryRow(ctx, getTransportByUuid, uuid)
	var i Transport
	err := row.Scan(
		&i.Uuid,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Url,
		&i.Title,
		&i.ImageUrl,
		&i.Notes,
		&i.Status,
		&i.BookingReference,
		&i.Selected,
		&i.BoardUuid,
	)
	return i, err
}

const updateTransportByUuid = `-- name: UpdateTransportByUuid :exec
update transport
set url = $1,
    title = $2,
    image_url = $3,
    notes = $4,
    status = $5,
    booking_reference = $6,
    selected = $7
where uuid = $8
`

type UpdateTransportByUuidParams struct {
	Url              string
	Title            string
	ImageUrl         *string
	Notes            *string
	Status           TransportStatus
	BookingReference *string
	Selected         bool
	Uuid             pgtype.UUID
}

func (q *Queries) UpdateTransportByUuid(ctx context.Context, arg UpdateTransportByUuidParams) error {
	_, err := q.db.Exec(ctx, updateTransportByUuid,
		arg.Url,
		arg.Title,
		arg.ImageUrl,
		arg.Notes,
		arg.Status,
		arg.BookingReference,
		arg.Selected,
		arg.Uuid,
	)
	return err
}
