// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT uuid, updated_at, created_at, email, name, avatar_url FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT uuid, updated_at, created_at, email, name, avatar_url FROM users WHERE uuid = $1 LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, uuid pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, uuid)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (email, name, avatar_url)
VALUES ($1, $2, $3)
ON CONFLICT (email)
DO UPDATE SET
    name = EXCLUDED.name,
    avatar_url = EXCLUDED.avatar_url,
    updated_at = now()
RETURNING uuid, updated_at, created_at, email, name, avatar_url
`

type UpsertUserParams struct {
	Email     *string
	Name      string
	AvatarUrl *string
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.Email, arg.Name, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
	)
	return i, err
}
