// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: votes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVote = `-- name: CreateVote :one
insert into votes (voted_by, rank, voted_on_, voted_on_uuid)
values ($1, $2, $3, $4)
returning uuid, updated_at, created_at, voted_by, rank, voted_on_, voted_on_uuid
`

type CreateVoteParams struct {
	VotedBy     pgtype.UUID
	Rank        int32
	VotedOn     VotedOn
	VotedOnUuid pgtype.UUID
}

func (q *Queries) CreateVote(ctx context.Context, arg CreateVoteParams) (Vote, error) {
	row := q.db.QueryRow(ctx, createVote,
		arg.VotedBy,
		arg.Rank,
		arg.VotedOn,
		arg.VotedOnUuid,
	)
	var i Vote
	err := row.Scan(
		&i.Uuid,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.VotedBy,
		&i.Rank,
		&i.VotedOn,
		&i.VotedOnUuid,
	)
	return i, err
}

const deleteVoteByUuid = `-- name: DeleteVoteByUuid :exec
delete from votes
where uuid = $1
`

func (q *Queries) DeleteVoteByUuid(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVoteByUuid, uuid)
	return err
}

const findAllVotesByVotedOnUuid = `-- name: FindAllVotesByVotedOnUuid :many
select v.uuid, v.updated_at, v.created_at, v.voted_by, v.rank, v.voted_on_, v.voted_on_uuid, u.name as user_name
from votes v
join users u on v.voted_by = u.uuid
where v.voted_on_ = $1 
    and v.voted_on_uuid = $2
`

type FindAllVotesByVotedOnUuidParams struct {
	VotedOn     VotedOn
	VotedOnUuid pgtype.UUID
}

type FindAllVotesByVotedOnUuidRow struct {
	Uuid        pgtype.UUID
	UpdatedAt   pgtype.Timestamp
	CreatedAt   pgtype.Timestamp
	VotedBy     pgtype.UUID
	Rank        int32
	VotedOn     VotedOn
	VotedOnUuid pgtype.UUID
	UserName    string
}

func (q *Queries) FindAllVotesByVotedOnUuid(ctx context.Context, arg FindAllVotesByVotedOnUuidParams) ([]FindAllVotesByVotedOnUuidRow, error) {
	rows, err := q.db.Query(ctx, findAllVotesByVotedOnUuid, arg.VotedOn, arg.VotedOnUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindAllVotesByVotedOnUuidRow
	for rows.Next() {
		var i FindAllVotesByVotedOnUuidRow
		if err := rows.Scan(
			&i.Uuid,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.VotedBy,
			&i.Rank,
			&i.VotedOn,
			&i.VotedOnUuid,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVoteByUuid = `-- name: UpdateVoteByUuid :exec
update votes
set rank = $1
where uuid = $2
`

type UpdateVoteByUuidParams struct {
	Rank int32
	Uuid pgtype.UUID
}

func (q *Queries) UpdateVoteByUuid(ctx context.Context, arg UpdateVoteByUuidParams) error {
	_, err := q.db.Exec(ctx, updateVoteByUuid, arg.Rank, arg.Uuid)
	return err
}
